"""empty message

Revision ID: 7db05014d135
Revises: f28197ce455c
Create Date: 2023-11-27 12:46:26.552378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7db05014d135'
down_revision = 'f28197ce455c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('horarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tomou', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('data', sa.DateTime(), nullable=True))
        batch_op.drop_column('id_etiqueta')

    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpf', sa.String(length=11), nullable=False))
        batch_op.add_column(sa.Column('chave_acompanhante', sa.String(length=255), nullable=False))
        batch_op.create_unique_constraint(None, ['chave_acompanhante'])
        batch_op.create_unique_constraint(None, ['cpf'])

    with op.batch_alter_table('posologias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duracao', sa.Integer(), nullable=False))
        batch_op.drop_column('dias_qtd')
        batch_op.drop_column('id_via')

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('celular', sa.String(length=255), nullable=False))
        batch_op.drop_constraint('usuarios_cpf_key', type_='unique')
        batch_op.create_unique_constraint(None, ['celular'])
        batch_op.drop_column('cpf')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpf', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('usuarios_cpf_key', ['cpf'])
        batch_op.drop_column('celular')

    with op.batch_alter_table('posologias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_via', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('dias_qtd', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('duracao')

    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('chave_acompanhante')
        batch_op.drop_column('cpf')

    with op.batch_alter_table('horarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_etiqueta', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('data')
        batch_op.drop_column('tomou')

    # ### end Alembic commands ###
