"""empty message

Revision ID: db0da17a330f
Revises: 7db05014d135
Create Date: 2023-11-27 15:08:40.867889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db0da17a330f'
down_revision = '7db05014d135'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpf', sa.String(length=11), nullable=False))
        batch_op.drop_constraint('usuarios_celular_key', type_='unique')
        batch_op.create_unique_constraint(None, ['cpf'])
        batch_op.drop_column('celular')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('celular', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('usuarios_celular_key', ['celular'])
        batch_op.drop_column('cpf')

    # ### end Alembic commands ###
